config/config/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'portfolio'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
]

portfolio/urls.py
from django.urls import path
from . import views

app_name = "portfolio"

urlpatterns = [
    path('', views.home_page_view, name='home'),
    path('sobre', views.sobre_page_view, name='sobre'),
    path('contacto', views.contacto_page_view, name='contacto'),
    path('educacao', views.educacao_page_view, name='educacao'),
    path('licenciatura', views.licenciatura_page_view, name='licenciatura'),
    path('projetos', views.projetos_page_view, name='projetos'),
    path('apis', views.apis_page_view, name='apis'),
    path('tfc/<int:pk>', views.tfc_detail_page_view, name='tfc_detail'),
    path('licenciatura', views.licenciatura_page_view, name='licenciatura'),
    path('blog', views.blog_page_view, name='blog'),
    path('novo_projeto', views.novo_projeto_page_view, name='novo_projeto'),
    path('editar_projeto/<int:projeto_id>', views.editar_projeto_page_view, name='editar_projeto'),
    path('nova_cadeira', views.nova_cadeira_page_view, name='nova_cadeira'),
    path('editar_cadeira/<int:cadeira_id>', views.editar_cadeira_page_view, name='editar_cadeira'),
    path('noticias', views.noticias_page_view, name='noticias'),
    path('laboratorios', views.laboratorios_page_view, name='laboratorios'),
    path('quizz', views.quizz_page_view, name='quizz'),
    path('login/', views.view_login, name='login'),
    path('logout/', views.view_logout, name='logout')
]

portfolio/models.py
from django.db import models
from django.core.validators import MinValueValidator 

def posts_resolution_path(instance, filename):
    return 'images/{0}/'.format(filename)

class Post(models.Model):
  autor = models.CharField(max_length=100)
  titulo = models.CharField(max_length=200)
  descricao = models.CharField(max_length=500)
  link = models.CharField(max_length=200, blank=True)
  imagem = models.ImageField(upload_to=posts_resolution_path, blank=True)
  criado = models.DateTimeField(auto_now_add=True)

  def __str__(self):
    return self.titulo[:50]

class PontuacaoQuizz(models.Model):
  nome = models.CharField(max_length=100)
  pontuacao = models.IntegerField(validators=[MinValueValidator(0)])
  criado = models.DateTimeField(auto_now_add=True)

  def __str__(self):
    return self.nome[:50]

class Linguagem(models.Model):
  nome = models.CharField(max_length=50)

  def __str__(self):
    return self.nome[:50]

class Professor(models.Model):
  nome = models.CharField(max_length=20)

  def __str__(self):
    return self.nome[:50]

class Projeto(models.Model):
  nome = models.CharField(max_length=100)
  disciplina = models.CharField(max_length=100, blank=True)
  ano_letivo = models.CharField(max_length=100, blank=True)
  tecnologias = models.CharField(max_length=100, blank=True)

  def __str__(self):
    return self.nome[:50]

class Cadeira(models.Model):
  nome = models.CharField(max_length=50)
  ano = models.IntegerField()
  descricao = models.TextField()
  linguagens = models.ManyToManyField(Linguagem)
  docente_teorica = models.ForeignKey(Professor, on_delete=models.CASCADE)
  docentes_praticas = models.ManyToManyField(Professor, related_name='caderias')
  projetos = models.ManyToManyField(Projeto)

  def __str__(self):
    return self.nome[:50]

class Tfc(models.Model):
  autores = models.CharField(max_length=500)
  ano = models.IntegerField()
  titulo = models.CharField(max_length=100)
  resumo = models.TextField()
  imagem = models.ImageField(upload_to=posts_resolution_path, blank=True)
  relatorio = models.CharField(max_length=100, blank=True)
  github = models.CharField(max_length=100, blank=True)
  video = models.CharField(max_length=100, blank=True)

  def __str__(self):
    return self.titulo[:100]

class Noticia(models.Model):
  titulo = models.CharField(max_length=100)
  descricao = models.TextField(max_length=100, blank=True)
  link = models.URLField(max_length=100, blank=True)

  def __str__(self):
    return self.titulo[:50]

class Laboratorio(models.Model):
  titulo = models.CharField(max_length=150)
  descricao = models.TextField(max_length=100, blank=True)
  link = models.URLField(max_length=100, blank=True)

  def __str__(self):
    return self.titulo[:50]

portfolio/forms.py
from django import forms
from django.forms import ModelForm
from .models import Post, Projeto, Cadeira


class PostForm(ModelForm):
  class Meta:
    model = Post
    fields = '__all__'
    widgets = {
      'titulo': forms.TextInput(),
      'autor': forms.TextInput(),
      'descricao': forms.Textarea(),
      'imagem': forms.FileInput(),
      'link': forms.URLInput(),
    }
    labels = {
      'autor': 'Autor',
      'titulo': 'Título',
      'descricao': 'Texto',
      'link': 'Link',
      'imagem': 'Imagem'
    }

    help_texts = {
    }

class ProjetoForm(ModelForm):
  class Meta:
    model = Projeto
    fields = '__all__'
    widgets = {
      'nome': forms.TextInput(),
      'disciplina': forms.TextInput(),
      'ano_letivo': forms.TextInput(),
      'tecnologias': forms.TextInput(),
    }
    labels = {
      'nome': 'Nome',
      'disciplina': 'Disciplina',
      'ano_letivo': 'Ano Letivo',
      'tecnologias': 'Tecnologias'
    }

    help_texts = {
    }

class CadeiraForm(ModelForm):
  class Meta:
    model = Cadeira
    fields = '__all__'
    widgets = {
    }
    labels = {
    }
    help_texts = {
    }

portfolio/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from datetime import datetime

from matplotlib import pyplot as plt
import io
import urllib, base64
import matplotlib
matplotlib.use('Agg')

from .models import Cadeira, Post, PontuacaoQuizz, Projeto, Tfc, Noticia, Laboratorio
from .forms import PostForm, ProjetoForm, CadeiraForm
from django.shortcuts import redirect

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

# Create your views here.
from django.shortcuts import render

def view_login(request):

  if request.method == 'POST':
    username = request.POST['username']
    password = request.POST['password']

    user = authenticate(
      request,
      username=username,
      password=password)

    if user is not None:
      login(request, user)
      return HttpResponseRedirect(reverse('portfolio:home'))
    else:
        return render(request, 'portfolio/login.html', {
            'message': 'Credenciais invalidas.'
        })

  return render(request, 'portfolio/login.html')

def view_logout(request):
  logout(request)

  return render(request, 'portfolio/login.html', {
      'message': 'Foi desconetado.'
  })

def home_page_view(request):
  agora = datetime.now()
  context = {
      'data': agora.date,
  }

  return render(request, 'portfolio/home.html', context)

def sobre_page_view(request):
  return render(request, 'portfolio/sobre.html')

def contacto_page_view(request):
  return render(request, 'portfolio/contacto.html')

def educacao_page_view(request):
  return render(request, 'portfolio/educacao.html')

def licenciatura_page_view(request):
  context = {
    'cadeiras': Cadeira.objects.all()
  }
  return render(request, 'portfolio/licenciatura.html', context)

def projetos_page_view(request):
  context = {
    'projetos': Projeto.objects.all(),
    'tfcs': Tfc.objects.all()
  }
  return render(request, 'portfolio/projetos.html', context)

def blog_page_view(request):
  form = PostForm(request.POST or None)
  if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:blog'))
  context = {
      'posts': Post.objects.all(),
      'form': form
  }
  return render(request, 'portfolio/blog.html', context)

def noticias_page_view(request):
  context = {
      'noticias': Noticia.objects.all()
  }
  return render(request, 'portfolio/noticias.html', context)

def laboratorios_page_view(request):
  context = {
      'laboratorios': Laboratorio.objects.all()
  }
  return render(request, 'portfolio/laboratorios.html', context)

def quizz_page_view(request):
  if request.method == 'POST':
    nome = request.POST['nome']
    pontos = pontuacao_quizz(request)
    if PontuacaoQuizz.objects.filter(nome=nome).exists():
      PontuacaoQuizz.objects.filter(nome=nome).update(pontuacao=pontos)
    else:
      query = PontuacaoQuizz(nome=nome, pontuacao=pontos)
      query.save()

    return redirect(reverse('portfolio:quizz'))

  context = {
    'data': desenha_grafico_resultados()
  }

  return render(request, 'portfolio/quizz.html', context)

def pontuacao_quizz(request):
  pontos = 0
  if request.method == 'POST':
    if request.POST['html'] == 'html1':
      pontos += 15
    if request.POST['image-tag'] == 'image-tag3':
      pontos += 15
    if request.POST['python'] == 'python2':
      pontos += 15
    return pontos

def desenha_grafico_resultados():
  query = sorted(PontuacaoQuizz.objects.all(),
                  key=lambda x: x.pontuacao, reverse=True)
  nomes = [objeto.nome for objeto in query]
  pontuacoes = [objeto.pontuacao for objeto in query]
  plt.barh(nomes, pontuacoes)
  plt.ylabel("Prioridade")
  plt.autoscale()

  fig = plt.gcf()
  plt.close()

  buf = io.BytesIO()
  fig.savefig(buf, format='png')


  buf.seek(0)
  string = base64.b64encode(buf.read())
  uri = urllib.parse.quote(string)

  return uri

def tfc_detail_page_view(request, pk):
  context = {
    'tfc': Tfc.objects.get(pk=pk)
  }
  return render(request, 'portfolio/tfc_detail.html', context)

def apis_page_view(request):
  return render(request, 'portfolio/apis.html')


def novo_projeto_page_view(request):

  if not request.user.is_authenticated:
    return HttpResponseRedirect(reverse('portfolio:login'))

  form = ProjetoForm(request.POST or None)

  if form.is_valid():
    form.save()
    return HttpResponseRedirect(reverse('portfolio:projetos'))

  context = {'form': form}
  return render(request, 'portfolio/novo_projeto.html', context)

def nova_cadeira_page_view(request):

  if not request.user.is_authenticated:
    return HttpResponseRedirect(reverse('portfolio:login'))

  form = CadeiraForm(request.POST or None)

  if form.is_valid():
    form.save()
    return HttpResponseRedirect(reverse('portfolio:licenciatura'))

  context = {'form': form}
  return render(request, 'portfolio/nova_cadeira.html', context)

@login_required
def editar_projeto_page_view(request, projeto_id):

    projeto = Projeto.objects.get(id=projeto_id)
    form = ProjetoForm(request.POST or None, instance=projeto)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:projetos'))

    context = {'form': form, 'projeto_id': projeto_id}
    return render(request, 'portfolio/editar_projeto.html', context)

def editar_cadeira_page_view(request, cadeira_id):

    cadeira = Cadeira.objects.get(id=cadeira_id)
    form = CadeiraForm(request.POST or None, instance=cadeira)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:licenciatura'))

    context = {'form': form, 'cadeira_id': cadeira_id}
    return render(request, 'portfolio/editar_cadeira.html', context)

portfolio/templates/portfolio/apis.html
{% extends 'portfolio/layout.html' %}

{% block main %}
  <section>
    <div class="container content content-center">
      <h1>API - Metereologia</h1>
      <div>
        <div class="form">
          <form class="weather-form">
            <label>Cidade <input type="text" class="weather-city" /></label>
            <button type="submit" class="btn-primary">Pesquisar</button>
          </form>
        </div>
        <div class="result-container hidden">
          <h2>Resultado - Metereologia</h2>
          <div class="result-fields">
            <strong>
              <p class="city-name"></p>
            </strong>
            <p class="city-temperature"></p>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section>
    <div class="container content content-center">
      <h1>API - Random Facts</h1>
      <div>
        <p>
          <strong>Facto:</strong> <span class="facts-result"></span>
        </p>
      </div>
    </div>
  </section>
{% endblock %}

{% block scripts %}
  {% load static %}
  <script type="text/javascript" src="{% static 'portfolio/scripts/apis.js' %}"></script>
{% endblock %}

portfolio/templates/portfolio/blog.html
{% extends 'portfolio/layout.html' %}

{% block main %}
  <section>
    <div class="container content content-center">
      <h1>Blog</h1>
      <div class="posts">
        {% for post in posts %}
          <div class="post">
            <h4>{{ post.titulo }}</h4>
            <p>{{ post.descricao }}</p>
            <div class="aditional-info">
              <div>
                {% if post.autor %}
                  <p class="author">{{ post.autor }}</p>
                {% endif %}
              </div>
              {% if post.link %}
                <a href="{{ post.link }}" class="btn-primary">Ver mais</a>
              {% endif %}
            </div>
          </div>
        {% endfor %}
      </div>

      <div class="posts-form">
        <h3>Criar post</h3>
        <form action="{% url 'portfolio:blog' %}" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form.as_p }}
          <div class="submit-group">
            <input type="submit" value="Gravar" class="btn btn-primary">
          </div>
        </form>
      </div>
    
    </div>
  </section>
      
{% endblock %}

portfolio/templates/portfolio/editar_cadeira.html
{% extends 'portfolio/layout.html' %}

{% block main %}
  <section>
    <div class="container content content-center">
      <div class="posts-form">
        <h1>Editar Cadeira</h1>
        <form action="{% url 'portfolio:editar_cadeira' cadeira_id %}" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form.as_p }}
          <div class="submit-group">
            <input type="submit" value="Gravar" class="btn btn-primary">
          </div>
        </form>
      </div>
    
    </div>
  </section>
      
{% endblock %}

portfolio/templates/portfolio/editar_projeto.html
{% extends 'portfolio/layout.html' %}

{% block main %}
  <section>
    <div class="container content content-center">
      <div class="posts-form">
        <h1>Editar Projeto</h1>
        <form action="{% url 'portfolio:editar_projeto' projeto_id %}" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form.as_p }}
          <div class="submit-group">
            <input type="submit" value="Gravar" class="btn btn-primary">
          </div>
        </form>
      </div>
    
    </div>
  </section>
      
{% endblock %}

portfolio/templates/portfolio/educacao.html
<!-- formacao.html -->

{% extends 'portfolio/layout.html' %}

{% block main %}
  <section>
    <div class="container">
      <h1>Educação</h1>
      <div class="posts">
        <div class="post">
          <h4>Licenciatura em Engenharia Informática</h4>
          <p>Universidade Lusófona de Humanidades e Tecnologias</p>
          <p><strong>Anos:</strong> 2020-2023</p>
          <div class="aditional-info">
            <div>
            </div>
            <a href="{% url 'portfolio:licenciatura' %}" class="btn-primary">Ver mais</a>
          </div>
        </div>
        <div class="post">
          <h4>Técnico de Gestão de Equipamentos Informáticos</h4>
          <p>Escola Técnica e Profissional de Mafra</p>
          <p><strong>Anos:</strong> 2012-2015</p>
          <div class="aditional-info">
            <div>
            </div>
            <a href="https://www.etpm.pt/tecnicodegestaodeequipamentosinformaticos" target="_blank" class="btn-primary">Ver mais</a>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

portfolio/templates/portfolio/laboratorios.html
{% extends 'portfolio/layout.html' %}

{% block main %}
  <section>
    <div class="container content content-center">
      <h1>Laboratórios</h1>
      <div class="posts">
        {% for laboratorio in laboratorios %}
          <div class="post">
            <h4>{{ laboratorio.titulo }}</h4>
            <p>{{ laboratorio.descricao }}</p>
            <div class="aditional-info">
              <div>
              </div>
              {% if laboratorio.link %}
                <a href="{{ laboratorio.link }}" class="btn-primary">Github</a>
              {% endif %}
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </section>
      
{% endblock %}

portfolio/templates/portfolio/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Ricardo Gonçalves - Portfolio</title>
  {% load static %}
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;700;800&display=swap" rel="stylesheet"/>
  <link rel="stylesheet" href="{% static 'portfolio/css/estilos.css' %}">
  <link rel="shortcut icon" href="{% static 'portfolio/images/favicon.ico' %}" />
</head>
<body>
  <header>
    <div>
      <a href="{% url 'portfolio:home' %}">Ricardo Gonçalves</a>
    </div>
    <nav>
      <a href="{% url 'portfolio:home' %}">Home</a>
      <a href="{% url 'portfolio:educacao' %}">Educação</a>
      <a href="{% url 'portfolio:projetos' %}">Projetos</a>
      <a href="{% url 'portfolio:laboratorios' %}">Laboratórios</a>
      <a href="{% url 'portfolio:blog' %}">Blog</a>
      <a href="{% url 'portfolio:noticias' %}">Noticias</a>
      <a href="{% url 'portfolio:quizz' %}">Quizz</a>
      <a href="{% url 'portfolio:apis' %}">Apis</a>
      <a href="{% url 'portfolio:sobre' %}">Sobre este Website</a>
      <a href="{% url 'portfolio:contacto' %}">Contacto</a>
      {% if request.user.is_authenticated %}
        <a href="{% url 'portfolio:logout' %}">Logout</a>
      {% else %}
        <a href="{% url 'portfolio:login' %}">Login</a>
      {% endif %}
    </nav>
  </header>
  <main>
    {% block main %}
    {% endblock main %}
  </main>
  <footer class="container">
    <div>
      <p>ULHT, 2022</p>
    </div>
    <div>
      <p>
        Ricardo Gonçalves - a22000492 - 2º Ano Licenciatura em Engenharia Informática
        <span class="time-slot"></span>
      </p>
    </div>
  </footer>

  {% block scripts %}
  {% endblock scripts %}

  {% load static %}
  <script type="text/javascript" src="{% static 'portfolio/scripts/main.js' %}"></script>
</body>
</html>

portfolio/templates/portfolio/licenciatura.html
{% extends 'portfolio/layout.html' %}

{% block main %}
  <section>
    <div class="container">
      <h1>Licenciatura em Engenharia Informática</h1>
      {% if request.user.is_authenticated %}
        <div>
          <a href="{% url 'portfolio:nova_cadeira' %}" class="btn-primary">Nova Cadeira</a>
        </div>
      {% endif %}
      <div class="posts">
        {% for cadeira in cadeiras %}
          <div class="post">
            <h4>{{ cadeira.nome }}</h4>
            <p>{{ cadeira.descricao }}</p>
            <p><strong>Ano:</strong> {{ cadeira.ano }}</p>
            {% if cadeira.linguagens %}
              <p><strong>Linguagens:</strong>
                {% for linguagem in cadeira.linguagens.all %}
                  {{ linguagem.nome }}
                {% endfor %}
              </p>
            {% endif %}
            <p><strong>Professor Teóricas:</strong> {{ cadeira.docente_teorica }}</p>
            <p><strong>Professores de Práticas:</strong> 
              {% for docente in cadeira.docentes_praticas.all %}
                  {{ docente.nome }}
                {% endfor %}
            </p>
            {% if request.user.is_authenticated %}
              <div class="aditional-info">
                <div>
                </div>
                <div>
                  <a href="{% url 'portfolio:editar_cadeira' cadeira.id %}" class="btn-primary">Editar</a>
                </div>
              </div>
            {% endif %}
          </div>
        {% endfor %}
      </div>
    </div>
  </section>
{% endblock %}

portfolio/templates/portfolio/login.html
{% extends 'portfolio/layout.html' %}

{% block main %}
  <section>
    <div class="container content content-center">
      <h1>Login</h1>
      {% if message %}
        <p> {{ message }} </p>
      {% endif %}
    
      <form action="" method="post" class="login-form">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Username">
        <input type="password" name="password" placeholder="Password">
    
        <input type="submit" value="Login" class="btn btn-primary">
      </form>
    </div>
  </section>

{% endblock %}

portfolio/templates/portfolio/noticias.html
{% extends 'portfolio/layout.html' %}

{% block main %}
  <section>
    <div class="container content content-center">
      <h1>Notícias</h1>
      <div class="posts">
        {% for noticia in noticias %}
          <div class="post">
            <h4>{{ noticia.titulo }}</h4>
            <p>{{ noticia.descricao }}</p>
            <div class="aditional-info">
              <div>
              </div>
              {% if noticia.link %}
                <a href="{{ noticia.link }}" class="btn-primary">Ver mais</a>
              {% endif %}
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </section>
      
{% endblock %}

portfolio/templates/portfolio/nova_cadeira.html
{% extends 'portfolio/layout.html' %}

{% block main %}
  <section>
    <div class="container content content-center">
      <div class="posts-form">
        <h1>Nova Cadeira</h1>
        <form action="{% url 'portfolio:nova_cadeira' %}" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form.as_p }}
          <div class="submit-group">
            <input type="submit" value="Gravar" class="btn btn-primary">
          </div>
        </form>
      </div>
    
    </div>
  </section>
      
{% endblock %}

portfolio/templates/portfolio/novo_projeto.html
{% extends 'portfolio/layout.html' %}

{% block main %}
  <section>
    <div class="container content content-center">
      <div class="posts-form">
        <h1>Novo Projeto</h1>
        <form action="{% url 'portfolio:novo_projeto' %}" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form.as_p }}
          <div class="submit-group">
            <input type="submit" value="Gravar" class="btn btn-primary">
          </div>
        </form>
      </div>
    
    </div>
  </section>
      
{% endblock %}

portfolio/templates/portfolio/projetos.html
<!-- projetos.html -->

{% extends 'portfolio/layout.html' %}

{% block main %}
  <section>
    <div class="container content content-center">
      <h1>Projetos</h1>
      {% if request.user.is_authenticated %}
        <div>
          <a href="{% url 'portfolio:novo_projeto' %}" class="btn-primary">Novo Projeto</a>
        </div>
      {% endif %}
      <div class="projetos">
        {% for projeto in projetos %}
          <div class="tfc">
            <h4>{{ projeto.nome }}</h4>
            <p>{{ projeto.disciplina }}</p>
            <p><strong>Ano letivo:</strong> {{ projeto.ano_letivo }}</p>
            <p><strong>Tecnologias:</strong> {{ projeto.tecnologias }}</p>
            {% if request.user.is_authenticated %}
              <div class="aditional-info">
                <div>
                </div>
                <div>
                  <a href="{% url 'portfolio:editar_projeto' projeto.id %}" class="btn-primary">Editar</a>
                </div>
              </div>
            {% endif %}
          </div>
        {% endfor %}
      </div>
    </div>
  </section>
  <section>
    <div class="container content content-center">
      <h1>Tfcs</h1>
      <p>Uma lista dos TFCs que mais me desperta interesse.</p>
      <div class="projetos">
        {% for tfc in tfcs %}
          <div class="tfc">
            <h4>{{ tfc.titulo }}</h4>
            <p><strong>Autores:</strong> {{ tfc.autores }}</p>
            <p><strong>Ano:</strong> {{ tfc.ano }}</p>
            <div class="aditional-info">
              <div>
              </div>
              <div>
                <a href="{% url 'portfolio:tfc_detail' tfc.id %}" class="btn-primary">Ver mais</a>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </section>
{% endblock %}

portfolio/templates/portfolio/sobre.html
<!-- apresentacao.html -->

{% extends 'portfolio/layout.html' %}

{% block main %}
  <section>
    <div class="container content">
      <div class="text-image">
        <div class="text-box spaced black">
          <h1>Sobre o website</h1>
          <p>Este website foi desenvolvido no âmbito de Programação Web ao longo da Licenciatura de Engenharia Informática.</p>
          <p>Foi utilizado HTML, CSS, JavaScript e Django no mesmo.</p>
        </div>
        <div class="center">
          {% load static %}
          <img src="{% static 'portfolio/images/programming2.jpg' %}" class="img-box">
        </div>
      </div>
    </div>
  </section>
  <section>
    <div class="container content content-center">
      <iframe width="560" height="315" src="https://www.youtube.com/embed/lugzR82bdmU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>
  </section>
{% endblock %}